void main(){
    int64_t i = 4;

    putchar('0' + (i == 4));
    putchar('\n');
    putchar('0' + (i != 5));
    putchar('\n');
    putchar('\n');
    putchar('0' + (i < 5));
    putchar('\n');
    putchar('0' + (i <= 5));
    putchar('\n');
    putchar('0' + (i <= 4));
    putchar('\n');
    putchar('\n');
    putchar('0' + (i > 3));
    putchar('\n');
    putchar('0' + (i >= 3));
    putchar('\n');
    putchar('0' + (i >= 4));
    putchar('\n');
    putchar('\n');
    putchar('0' + (i + 3));
    putchar('\n');
    putchar('0' + (i - 3));
    putchar('\n');
    putchar('\n');
    putchar('0' + (i * 2));
    putchar('\n');
    putchar('0' + (i / 2));
    putchar('\n');
    putchar('0' + (i % 3));
    putchar('\n');
    putchar('\n');
    putchar('0' + (i >> 2));
    putchar('\n');
    putchar('0' + (i << 1));
    putchar('\n');
    putchar('\n');
    putchar('0' + (i++));
    putchar('\n');
    putchar('0' + (i--));
    putchar('\n');
    putchar('0' + (i));
    putchar('\n');
    putchar('0' + (++i));
    putchar('\n');
    putchar('0' + (--i));
    putchar('\n');
    putchar('\n');
    putchar('0' + (i = 3));
    putchar('\n');
    putchar('0' + (i += 3));
    putchar('\n');
    putchar('0' + (i -= 3));
    putchar('\n');
    putchar('0' + (i *= 3));
    putchar('\n');
    putchar('0' + (i /= 3));
    putchar('\n');
    putchar('0' + (i %= 2));
    putchar('\n');
    putchar('\n');
    putchar('0' + (i <<= 3));
    putchar('\n');
    putchar('0' + (i >>= 1));
    putchar('\n');
    putchar('\n');
    putchar('0' + (i = 5));
    putchar('\n');
    i &= 2;
    putchar('0' + (i));
    putchar('\n');
    i = 2;
    i ^= 3;
    putchar('0' + (i));
    putchar('\n');
    i = 4;
    i |= 2;
    putchar('0' + (i));
    putchar('\n');
    putchar('\n');
    putchar('\n');
    i = 3;
    putchar('0' + (i == 3 && i >= 1));
    putchar('\n');
    putchar('0' +  (i == 2 || i <= 9));
    putchar('\n');
    putchar('\n');
    putchar('0' + ((-i) + 6));
    putchar('\n');
    putchar('0' + ((+i) + 6));
    putchar('\n');
    putchar('0' + ((!i)));
    putchar('\n');
    putchar('0' + ((!0)));
    putchar('\n');
    putchar('0' + ((~(-5))));
    putchar('\n');

}