

#ifndef ANTLR4CPP_FETCHER_EXPRMULTIPLICATIVEOPERATION_H
#define ANTLR4CPP_FETCHER_EXPRMULTIPLICATIVEOPERATION_H


class ExprMultiplicativeOperation {

};


#endif //ANTLR4CPP_FETCHER_EXPRMULTIPLICATIVEOPERATION_H
