//
// Created by julien on 3/14/18.
//

#ifndef ANTLR4CPP_FETCHER_IFSTATEMENTINSTRUCTION_H
#define ANTLR4CPP_FETCHER_IFSTATEMENTINSTRUCTION_H

class IfStatementInstruction{

};

#endif //ANTLR4CPP_FETCHER_IFSTATEMENTINSTRUCTION_H
