

#ifndef ANTLR4CPP_FETCHER_EXPREQUALITYCOMPARAISONOPERATION_H
#define ANTLR4CPP_FETCHER_EXPREQUALITYCOMPARAISONOPERATION_H


class ExprEqualityComparaisonOperation {

};


#endif //ANTLR4CPP_FETCHER_EXPREQUALITYCOMPARAISONOPERATION_H
