

#ifndef ANTLR4CPP_FETCHER_EXPRBINARYSHIFTOPERATION_H
#define ANTLR4CPP_FETCHER_EXPRBINARYSHIFTOPERATION_H


class ExprBinaryShiftOperation {

};


#endif //ANTLR4CPP_FETCHER_EXPRBINARYSHIFTOPERATION_H
