#ifndef MAPLECOMPILER_DECLARATIONS_H
#define MAPLECOMPILER_DECLARATIONS_H

#include <accessor/Accessor.h>
#include <accessor/FunctionAccessor.h>
#include <accessor/LeftValue.h>
#include <accessor/LeftValueAccessor.h>
#include <accessor/LeftValueTab.h>
#include <accessor/LeftValueVar.h>
#include <array/TabAccessor.h>
#include <array/TabDeclaration.h>
#include <axiom/Start.h>
#include <control-structure/Block.h>
#include <control-structure/Instruction.h>
#include <control-structure/IfStatement.h>
#include <control-structure/ReturnStatement.h>
#include <control-structure/Statement.h>
#include <control-structure/WhileStatement.h>
#include <declaration/Declaration.h>
#include <expression/Expr.h>
#include <expression/ExprAccessor.h>
#include <expression/ExprAffectation.h>
#include <expression/ExprIncrement.h>
#include <expression/ExprParenthesis.h>
#include <expression/ExprValue.h>
#include <expression/Value.h>
#include <expression/operation/binary/ExprBinaryAndOperation.h>
#include <expression/operation/binary/ExprBinaryOrOperation.h>
#include <expression/operation/binary/ExprBinaryShiftOperation.h>
#include <expression/operation/binary/ExprBinaryXorOperation.h>
#include <expression/operation/binary/ExprBinaryOperation.h>
#include <expression/operation/ExprAdditiveOperation.h>
#include <expression/operation/ExprAndOperation.h>
#include <expression/operation/ExprEqualityComparisonOperation.h>
#include <expression/operation/ExprMultiplicativeOperation.h>
#include <expression/operation/ExprOrOperation.h>
#include <expression/operation/ExprOperation.h>
#include <expression/operation/ExprRelationalComparisonOperation.h>
#include <expression/unary/ExprPrefixUnary.h>
#include <expression/unary/ExprUnary.h>
#include <function/AccessorFunction.h>
#include <function/BlockFunction.h>
#include <function/FunctionDefinition.h>
#include <function/FunctionParam.h>
#include <symbol-table/SymbolTable.h>
#include <symbol-table/Symbol.h>
#include <variable/VarAccessor.h>
#include <variable/VarDeclaration.h>

#endif //MAPLECOMPILER_DECLARATIONS_H
